# Generated by Django 3.1.5 on 2021-01-21 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialused', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Worked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UsersAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('uname', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('estimated_date', models.DateField()),
                ('review', models.IntegerField(blank=True, null=True)),
                ('material_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.material')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.worked')),
            ],
        ),
    ]
